### ISSUE TITLE
Failed automatic import after debian, FreeBSD boots.

### ISSUE THREAD

**Issue by atisharma** [zbm-dev/zfsbootmenu#171]
Firstly, thank you for the interesting software. Root on ZFS is a great thing.

I have a detached UEFI setup (/boot/efi on a USB with refind) with both void and debian.
I also have a separate disk with FreeBSD (and its own EFI partition).
The home directory is shared between void and FreeBSD (but not yet with debian).
So, relevant the pools/datasets look like

```
zlinux                 197G   702G       96K  none
zlinux/ROOT           14.0G   702G       96K  none
zlinux/ROOT/debian     959M   702G      959M  /
zlinux/ROOT/void      13.0G   702G     12.3G  /
zlinux/home           31.4G   702G       96K  /home
zlinux/home/asharma   30.8G   702G     29.4G  /home/asharma
[...]
zlinux/venv           2.88G   702G     2.88G  legacy
zbsd                  7.76G   221G       96K  none
zbsd/ROOT             7.04G   221G       96K  none
zbsd/ROOT/default     7.04G   221G     7.04G  /
zbsd/tmp               480K   221G      480K  /tmp
...
zbsd/venv             13.2M   221G     13.2M  legacy
```

(aside: while it would be great if booting to FreeBSD was supported, I guess it's impossible with the kexec hand-off method.)

After using FreeBSD or debian, when I reboot to zfsbootmenu, the pool import fails.
I am able to continue with
`zpool import -f zlinux`
but I would like to know how to avoid this (for instance, so I can leave the boot unattended).

I guess there is a difference with how the pools are exported or left at shutdown between void and the others; if it requires a config step it would be nice to document it.

**Comment by ahesford** [comment]
It's long been a dream of mine to boot a FreeBSD kernel from ZFSBootMenu. Apparently petitboot on OpenPOWER uses a modified kexec to accomplish this, but we have not had the time or serious motivation to investigate the effort required to bring similar capabilities for ZFSBootMenu.

The issue seems to be disagreement between host IDs between your ZFSBootMenu image (which probably agrees with Void), Debian and (apparently) FreeBSD. I don't know how FreeBSD handles the host ID during boot, but I am pretty sure `initramfs-tools` from Debian leaves `/etc/hostid` out of your initramfs, which means it is probably importing your pool with a zero hostid. We have fought the host ID problem for awhile, but we now have mechanisms in place to fight these issues.

You have several options. If you just want simplicity, make sure rEFInd boots your ZFSBootMenu image (v1.9.0 or newer) with kernel command-line arguments

    zbm.prefer=zlinux zbm.import_policy=hostid zbm.set_hostid

in addition to whatever arguments you are already specifying.

You set `zbm.prefer=zlinux` so that ZFSBootMenu will try its best to import `zlinux` before any others. Without a preference, ZFSBootMenu may be able to import `zbsd` without any host-ID antics and not care if `zlinux` fails to import.

The `zbm.import_policy=hostid` option will cause ZFSBootMenu to attempt to match its host ID to whatever the ZFS says was last used to import the pool. It will first try to import the preferred pool (or, without one, any pool) using whatever host ID is encoded in its image; if nothing can be imported, it will scrape the failure message for the host ID last used to import the pool. It will try again and, if the import succeeds with a new host ID, will also attempt to import any other pools with the adopted ID.

The `zbm.set_hostid` option will cause ZFSBootMenu to rewrite the kernel command-line arguments it passes to your boot environment, setting `spl.spl_hostid=<hostid>` to whatever host ID is currently in use. Note that dracut-based systems like Void tend to favor `spl_hostid`, which is ignored by the ZFS kernel modules but causes the initramfs to write the provided value to `/etc/hostid` before importing anything. The `initramfs-tools` and `mkinitcpio` initramfs generators provide no such option, so `spl_hostid` would be ignored. Using `spl.spl_hostid` instead forces the value in the kernel module. When this is specified and non-zero, this supersedes any value in `/etc/hostid` and works on all Linux distributions.

If you want to be "correct", you can instead figure out what host ID FreeBSD is using to import `zlinux` and apply that consistently everywhere. This will also avoid the slight delay from `zbm.import_policy=hostid` when the initial import fails, but I doubt you'll detect the delay anyway. I'm not sure how ZFS on FreeBSD handles host IDs, but when you reboot to ZFSBootMenu after FreeBSD, you can just run `zpool import zlinux` and read the failure message to see what host ID is recorded in the pool. Copy that value. In both Void and Debian, you should then run

    zgenhostid -f <freebsd-value>

to force `/etc/hostid` to match what FreeBSD is providing. In Void, after `zgenhostid`, you should recreate your initramfs images:

    dracut -f -q --regenerate-all

and then re-run `generate-zbm` to create a ZFSBootMenu image with the desired host ID.

For Debian, you can either figure out how to include `/etc/hostid` in its initramfs (I couldn't find this with ~30s of web searches), or you can rely on `spl.spl_hostid`. You can still boot ZFSBootMenu with the `zbm.set_hostid` option to force add it, or you can add `spl.spl_hostid=0x<freebsd-value>` to whatever other arguments you are passing to the boot environment via the `org.zfsbootmenu:commandline` property. (Note that `spl.spl_hostid` is parsed as an integer, so if written in hex, it must have a leading `0x`.)

**Comment by atisharma** [comment]
Thank you for your excellent reply.

I tried your 'correct' approach for FreeBSD and it worked. There is some complaining about unsupported features on the zpool (dmraid) because I upgraded the pool in FreeBSD -- but that's unavoidable.

### Further information
FreeBSD stores and sets its hostid via `sysctl kern.hostid` as a decimal. This can be persistently set.
I confirmed this is the same hostid as reported by the failed `zpool import` in zfsbootmenu. In FreeBSD, the file `/etc/hostid` contains a UUID and seems to be unrelated.

Out of curiosity, I tried at first to modify the FreeBSD hostid to match the linux one via sysctl, but the imports still failed reporting various hostids on the failed import. I am not sure why.

I will proceed to the debian question.

**Comment by atisharma** [comment]
Just to note, the wiki entry for debian says `zfs set org.zfsbootmenu:commandline="spl_hostid=$( hostid ) ro quiet" zroot/ROOT` but above you mention requiring a `0x` in front.

**Comment by ahesford** [comment]
`spl_hostid` and `spl.spl_hostid` have different semantics; dracut uses the `spl_hostid` to write `/etc/hostid` and should be a hex number *without* the leading `0x`. The ZFS SPL kmod never actually sees this argument. Instead, it uses `spl.spl_hostid` to control its internal behavior and requires a leading `0x` for hex values.

**Comment by atisharma** [comment]
I looked but could not find out how to include `/etc/hostid` in debian's initramfs.

I now understand from your reply the difference between `spl.spl_hostid` and `spl_hostid`.

I set `org.zfsbootmenu:commandline` as you explained to `spl.spl_hostid=0x$(hostid) ro quiet`.
I also did `apt install --yes zfs-initramfs` when in chroot and set up the service in step [_11 "Enable importing bpool"_](https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Buster%20Root%20on%20ZFS.html) of the openzfs docs for Buster. I also copied over /etc/hostid.

I can confirm that I now have debian bullseye (originally installed via chroot debootstrap from void) booting via zfsbootmenu, and leaving its zpool in a state that imports without error in zfsbootmenu.

Since both the debian and FreeBSD questions have been resolved, I will close the issue.

Thank you again for your kind help, which is both extensive and accurate. I expect others will benefit from it in the future.
