### ISSUE TITLE
authentication for boot menu

### ISSUE THREAD

**Issue by Dragon-debian** [zbm-dev/zfsbootmenu#229]
Is there a way or plan to protect the boot menu from unauthenticated people?
I know that if pool is encrypted, user needs to enter pool password, but is it the only way to authenticate the user?

**Comment by zdykstra** [comment]
I'm unclear on what you're looking to accomplish here. If you'd like to prevent changes to the ZFSBootMenu EFI executable, it should be signed with your secure boot key so that it won't load if it's been tampered with.

**Comment by ericonr** [comment]
If I understand correctly, you want something like firmware level access password. I believe most BIOS and UEFI implementations offer that functionality.

I don't know if it's in scope for zbm to implement a password prompt to users. It would greatly increase the maintenance burden, given all the care that would have to be taken.

**Comment by Dragon-debian** [comment]
I mean something like grub password. but I think its beyond dracut capabilities and this project.
I already generate  EFI images and sign them with my key.

**Comment by ahesford** [comment]
The GRUB password is pointless security theater. You aren't preventing somebody from accessing your disk and you aren't preventing them from booting the system; you are just making them use a different bootloader to boot your system.

If you want security against unauthorized access to the contents of your system, you encrypt your filesystems and trust some people with passphrases to unlock them. You might as well trust those people to boot your system as well, because that's the least of your worries.

Secure Boot provides you a means to ensure that nobody tampers with your bootloader and installs some nefarious software to capture your secrets. Beyond that, "authentication" in ZFSBootMenu means "the person was able to unlock the disk, there's nothing more to protect."

Of course, we try to make ZBM as flexible and extensible as possible. You can put together whatever access controls you want as an early setup hook that ZBM will execute before it imports any pools.
