### ISSUE TITLE
How can I select a different initramfs for a given kernel?

### ISSUE THREAD

**Issue by csarn** [zbm-dev/zfsbootmenu#246]
As far as I understand, zfsbootmenu guesses the initramfs from the kernel name. If it finds a matching file, that file is used.
Is there any way to select a different initramfs?
I'd like options to both
- select initramfs from the menu
- set a custom default initramfs i.e. via zfs properties

**Comment by ahesford** [comment]
This has come up before, but we don't have a good proposal for how it works. A kernel-selector submenu that allows custom selection of the initramfs for a given kernel would take a bit of work but would be minimally invasive.

A property that allows automatic configuration would be much more difficult and prone to explode. I'd be open to considering proposals, but short of defining some template string, I think most options would be very fragile.

Maybe an acceptable alternative to a property would be looking first for a symlink, say /boot/${kernel}.initramfs or something, that points to the actual initramfs you'd like to use. That could be updated from R/W chroot before boot or any time from a running system. If the link doesn't exist or doesn't point to a valid path, we can just fall back to the usual selection mechanism.

**Comment by csarn** [comment]
The fragility coming from systems that put kernel version numbers into the initramfs-names, I assume?
In such cases the user would also need to update the symlink accordingly, if he wants to choose his own default initramfs.
The fallback to the usual selection mechanism would be possible for both the symlink variant and the zfs property variant of setting initramfs selections, so I'm not sure one would gain a lot from choosing symlinks.
Rather, the configuration for zfsbootmenu is now spread across different locations, being properties and symlinks.

I'll think about it a little more, and maybe try to implement at least the menu for initramfs selection.

**Comment by zdykstra** [comment]
I'm not sure violating the 1-to-1 mapping of kernel/initramfs is a good idea. However, I believe we already have everything needed right now to make this function as you expect. On an Alpine system, I was able to setup the following /boot structure:

```
ztest/ROOT/alpine /boot > ls -lah
total 103M
drwxr-xr-x    3 root     root          10 Jan 11 14:30 .
drwxr-xr-x   21 root     root          21 Nov 29 15:38 ..
-rw-r--r--    1 root     root        4.1M Nov 26 11:51 System.map-lts
lrwxrwxrwx    1 root     root           1 Nov 29 15:39 boot -> .
-rw-r--r--    1 root     root      227.6K Nov 26 11:51 config-lts
-rw-------    1 root     root       46.9M Nov 29 16:01 initramfs-lts
-rw-------    1 root     root       46.9M Jan 11 14:30 initramfs-lts-test
drwxr-xr-x   14 root     root          15 Nov 29 16:02 unpack
-rw-r--r--    1 root     root        7.5M Nov 26 11:51 vmlinuz-lts
lrwxrwxrwx    1 root     root          11 Jan 11 14:30 vmlinuz-lts-test -> vmlinuz-lts
```

The existing kernel selection mechanism correctly paired/matched `vmlinuz-lts-test` to `initramfs-lts-test`. When you create the additional initramfs images in `/boot`, your creation script / process could simply symlink the kernel to line up with the initramfs name. Anything after `vmlinuz-` and `initramfs-` is considered a version.

**Comment by ahesford** [comment]
A symlink works better because it is tied to a specific kernel in an obvious fashion (because the link can be named identically to the kernel, with some suffix appended). The `org.zfsbootmenu:kernel` property is interpreted as a regular expression that bash matches against the full path to the kernel; this can be a complete file name (which is what happens when you set the default kernel from a ZBM menu) or some version string like `5.10` or `5.15.2` to provide less specificity. ZBM also does the right thing when no match is found, and just picks the most recent kernel it finds.

A property that specifies an initramfs presents several pitfalls that must be avoided:
- A full path to an initramfs is bad because a kernel may be selected by fuzzy match and a specific initramfs is not guaranteed to work with whatever satisfies the fuzzy match.
- A fuzzy match rule like we use for the kernel means we have two independent selection criteria for a pair of things that *must* properly paired.
- Some kind of template scheme (*e.g.*, allowing things like `initramfs-%{version}.img` in the property) means we have to implement a template engine in bash to allow arbitrary selections (we already do this for `%{parent}` in the KCL property, but that's pretty ugly and doesn't have the pairing problem the kernel and initramfs have).

As @zdykstra notes, you can already make this work with symlinks given our matching scheme. However, I would still be open to the idea that we prefer initramfs images of the form `/boot/${kernel}.initramfs` if they exist, which would allow you to definitively nominate an initramfs image for each kernel.

**Comment by ahesford** [comment]
Actually, after further review, we already do give preference for a very specific kernel file. If the kernel is available at `/boot/${kernel}` (say `kernel=vmlinuz-5.15.2_1`), then the first match for initramfs is always `initramfs-${kernel}.img`; only of that file can't be found will it try to strip some version and look for things like `initramfs-${version}`.

**Comment by csarn** [comment]
@zdykstra That is a good idea! Maybe this already completely satisfies what I want to acheive. I could also set org.zfsbootmenu:kernel to that symlink if I want the corresponding initramfs as a default.

Maybe all that's needed is adding this tip to the documentation :)

**Comment by zdykstra** [comment]
> @zdykstra That is a good idea! Maybe this already completely satisfies what I want to acheive. I could also set org.zfsbootmenu:kernel to that symlink if I want the corresponding initramfs as a default.
> 
> Maybe all that's needed is adding this tip to the documentation :)
> 
> 

Did this end up working for you?

**Comment by csarn** [comment]
Yes, it is working, thanks! I'll close this issue.
