### ISSUE TITLE
ZFSBootMenu booting off of USB mirror drives

### ISSUE THREAD

**Issue by TheDrifter363** [zbm-dev/zfsbootmenu#265]
Hi,

So I have 2 32 GB usb drives. I've installed Debain on them, with root on ZFS. They also have a 512 MB fat32 partition that hold those premade EFIs available to download.

Problem is, I can boot off of those EFIs but they don't detect the USB pool. They can detect my internal HDD pool just fine, but the USB one, they just don't recognize it. So I get prompted to a recovery shell, where I have to do "zpool import rpool", and then when I exit the shell, the normal kernel option to boot of comes up. So I'm not sure what the issue is? Something about the USB detection? Those premade EFIs can't detect pools on USB drives? Any ideas? 

I really liked the convenience of those EFIs, instead of using a bootloader. It's great for servers.

**Comment by zdykstra** [comment]
USB drives usually take a little bit longer to be discovered. Since the pool does eventually show up, you can add `zbm.prefer=rpool!` to your ZBM command line. That will cause it to enter a retry loop after it fails to find an importable pool. The loop can be interrupted in the event that you need to access a recovery shell - but it will otherwise loop forever until `rpool` becomes available. By default it waits 5 seconds between attempting to find/import pools; you can increase or decrease this timeout via `zbm.import_delay=`.

**Comment by TheDrifter363** [comment]
Cool thanks so much! So would I add this with the command efibootmgr? Is there a command line option for that? I'll take a look at the manpage anyway, just thought I'd ask.

**Comment by zdykstra** [comment]
Yup, when you add a boot entry with `efibootmgr`, you would add am option for it then. The flag should be `--unicode 'zbm.prefer=rpool!'`, but I haven't used efibootmgr recently so that might not be entirely correct.

**Comment by ahesford** [comment]
You might be able to edit the image without trying to force your UEFI implementation to pass arguments to the boot executable. You can try
```bash
objcopy --dump-section .cmdline=/tmp/zbmkcl.txt /path/to/original/zfsbootmenu.EFI
```
This will create the file `/tmp/zbmkcl.txt` with the original command line. Edit this file, adding `zbm.prefer=rpool!` to the end of the line. (All arguments should be on a single line in this file.) You may need to make sure that there is a space at the end of the line; I see some extra garbage in the `lsinitrd` dump of the command line when adding an argument with this method, but that garbage goes away if I add a trailing space in the text file. After saving the edited KCL file, run
```bash
objcopy --update-section .cmdline=/tmp/zbmkcl.txt /path/to/original/zfsbootmenu.EFI /path/to/new/zfsbootmenu.EFI
```
to create a modified EFI file. Try to boot that, but keep the other around just in case.

If this works for you, we may add a simple tool that will make editing the encoded KCL more convenient.

**Comment by zdykstra** [comment]
You might need to instead try:

```
objcopy --dump-section .cmdline=/tmp/zbmkcl.txt /path/to/original/zfsbootmenu.EFI
objcopy --remove-section .cmdline /path/to/original/zfsbootmenu.EFI /path/to/new/zfsbootmenu.EFI
```

Edit /tmp/zbmkcl.txt, leaving a trailing space

```
objcopy --add-section .cmdline=zbmkcl.txt --change-section-vma .cmdline=0x30000 /path/to/new/zfsbootmenu.EFI
```

**Comment by jrtoddy** [comment]
Another slightly more flexible possibility is to use [`rEFInd`](https://www.rodsbooks.com/refind/) as your boot manager, and then use rEFInd to execute the ZFSBootMenu kernel and initramfs image directly rather than the EFI bundle.

That way, one can edit the kernel options easily in plain text by making changes in `refind.conf` - handy if you're doing lots of tweaking/fiddling.

Here a snippet of my rEFInd+ZBM-on-USB setup -
 
#### On the EFI System Partition
```
/EFI/BOOT/bootx64.efi [refind_x64.efi]
/EFI/BOOT/refind.conf

/EFI/BOOT/[various other contents of the refind-bin-<version>.zip]
     ./icons
     ./vars
     ./drivers_*
     ./tools_*

/zbm-kernel/initramfs-bootmenu.img
/zbm-kernel/vmlinuz-bootmenu
[from ...zfsbootmenu/releases/download/v1.12.0/zfsbootmenu-release-x86_64-v1.12.0.tar.gz]
```

By default on many systems, `/EFI/BOOT/bootx64.efi` will be launched even if it's not configured in the EFI NVRAM  - effectively making your USB stick pool portable - so I simply `cp refind_x64.efi bootx64.efi` here.

Similarly, if you have configured your EFI to your liking, you could place the ZBM EFI as `/EFI/BOOT/bootx64.efi` and directly launch it.

#### refind.conf

You would need an entry something like this...

```
menuentry "ZFSBootMenu " {
        loader /zbm-kernel/vmlinuz-bootmenu
        initrd /zbm-kernel/initramfs-bootmenu.img

        options "ro loglevel=4 nomodeset zbm.prefer=<yourzfspoolname>!"
}
```
#### In theory...

In theory, using the correct configuration options in rEFInd and ZFSBootMenu, you could have near-silent, non-interactive automatic boot of your USB stick pool, with portability, but still have the flexibility of calling up rEFInd and ZFSBootMenu in full when required; no fiddling with the EFI NVRAM required.
