### ISSUE TITLE
bash doesnt show long lines correctly in recovery shell and chroot

### ISSUE THREAD

**Issue by Dragon-debian** [zbm-dev/zfsbootmenu#288]
If you type a long command that doesnt fit on a single line, in recovery shell or chroot environment, it starts to overlap itself.

e.g.
you type this:
```bash
THIS IS A VERY LONG COMMAND THAT DOESNT FIT IN A SINGLE LINE
```
after the line hits the maximum length of screen, bash shows remaining of it from the beginning of the current line, overlaping the prompt and what was on the line before.

Its somehow related to `PS1`, I accidentaly found that by changing `PS1` to something else, bash shows lines correctly.

**Comment by zdykstra** [comment]
Thanks for the bug report. I believe I have this fixed in [fix-ps1](https://github.com/zbm-dev/zfsbootmenu/tree/fix-ps1).  Please test this locally to let me know if the issue is resolved for you. Pre-built images from that branch/commit are available for download at https://github.com/zbm-dev/zfsbootmenu/actions/runs/2180360281 .

**Comment by Dragon-debian** [comment]
I tested release components and recovery components, both work fine and the problem is solved.
