### ISSUE TITLE
[FEATURE REQUEST] Templates for advanced LUKS unlocking

### ISSUE THREAD

**Issue by PoisonFrog** [zbm-dev/zfsbootmenu#315]
I know ZBM works with LUKS, but I feel it is lacking a script that gives it the capabilities to unlock another drive to get to the headers and keyfiles like GRUB does. I know it is possible with user made scripts but GRUB has its config file where you just need to place the ID of your disks and location of headers and keyfiles and its scripts take care of it and it would be great if ZBM also had something like this so the user doesn't need to write their own half-assed scripts.

Since ZBM uses fzf it could display all the LUKS encrypted drives (maybe even truecrypt/veracrypt drives too) available for unlocking and once the user picks one and unlocks the drive it finds a follow-up script inside the encrypted drive that points to the location of headers/keyfiles and disk IDs for unlocking. In this case all the user would need to do would  is dropping the follow-up script inside the encrypted drive and placing the files it needs in there (and add the first script to early hooks or just turn on an option).

I would write this myself and share if I were any good at bash scripting.

**Comment by ahesford** [comment]
This is a tough one. We've been thinking a bit about how LUKS fits into ZFS pools and, for a pool composed of a single disk, it's pretty easy to do just by adding LUKS support to Dracut and letting it do its thing. Unfortunately, for multiple-disk pools, it quickly gets messy. Things are made more difficult because both @zdykstra and I stick with native encryption. (For all the bad press ZFS native encryption sometimes gets, it does a nice job solving a lot of problems of convenience.) It's difficult to propose a meaningful solution when neither of us has any real opinions.

Another issue is that it's hard to see how "official" LUKS support could be included without strict requirements on how zpools are constructed. We strive to keep ZFSBootMenu as free from assumptions about pool configuration as possible so that people can deploy it on all sorts of exotic configurations. Telling people how they must construct LUKS pools for support undermines that effort. To make matters worse, supporting multiple disks in a pool probably also requires specialty support in your distribution initramfs, which lives outside the realm of ZFSBootMenu.

If any of us get into LUKS as a replacement for native encryption, it will probbly come in the form of a dracut/mkinitcpio module separate from this project that could be incorporated into both your ZBM and distribution initramfs images. As a separate project, I'd have no qualms about taking strong(er) positions about pool configuration than we want to make in ZBM. As long as the module knows how to unlock everything before ZFS tries to import, it should provide the pieces necessary to make this possible.

**Comment by PoisonFrog** [comment]
> This is a tough one. We've been thinking a bit about how LUKS fits into ZFS pools and, for a pool composed of a single disk, it's pretty easy to do just by adding LUKS support to Dracut and letting it do its thing. Unfortunately, for multiple-disk pools, it quickly gets messy. Things are made more difficult because both @zdykstra and I stick with native encryption. (For all the bad press ZFS native encryption sometimes gets, it does a nice job solving a lot of problems of convenience.) It's difficult to propose a meaningful solution when neither of us has any real opinions.
> 
> Another issue is that it's hard to see how "official" LUKS support could be included without strict requirements on how zpools are constructed. We strive to keep ZFSBootMenu as free from assumptions about pool configuration as possible so that people can deploy it on all sorts of exotic configurations. Telling people how they must construct LUKS pools for support undermines that effort. To make matters worse, supporting multiple disks in a pool probably also requires specialty support in your distribution initramfs, which lives outside the realm of ZFSBootMenu.
> 
> If any of us get into LUKS as a replacement for native encryption, it will probbly come in the form of a dracut/mkinitcpio module separate from this project that could be incorporated into both your ZBM and distribution initramfs images. As a separate project, I'd have no qualms about taking strong(er) positions about pool configuration than we want to make in ZBM. As long as the module knows how to unlock everything before ZFS tries to import, it should provide the pieces necessary to make this possible.

I believe the method I proposed is compatible with any kind of LUKS configuration because it isn't opening the LUKS containers  where pools are stored, it is opening the containers where secrets are stored and where instructions to unlock the containers are. I believe this can be use with any kind of configuration, especially multiple disk pools. Yet I understand your points and I don't think this kind of feature would appeal to many users anyways.
