### ISSUE TITLE
Feature request that is 100% beyound scope and a dumb question about your code (apologies in advance :)

### ISSUE THREAD

**Issue by developer91234** [zbm-dev/zfsbootmenu#328]
I'd like to have something like this but for BTRFS. Assuming you have no interest in adding BTRFS support to this project (if you do, you can stop reading lol) I'd like to ask a couple of dumb questions so I can start working on a "btrfsbootmenu" myself as a hobby project:

* How are you actually using fzf and kexec-tools here? I searched the code and I can't see how you're embedding these packages in the initramfs. I guess I could add them via `dracut.conf` `install_items+` but it doesn't seem to be how you do it.
* What source files should I read first to get a basic idea of how zbm works internally?

I have basically no experience with lower level linux programming (so not counting scripting etc. in the context of a fully booted system, installation scripts and so on) but I really want this functionality for btrfs and need to know where to start. Not asking for too much detail here just a few entry points - I'll try to figure out the rest on my own.

**Comment by abenson** [comment]
I feel that is out of scope for this project.

**Comment by ahesford** [comment]
We are most definitely not interested in trying to support btrfs, but have a look through what we do and have fun adapting it.

I think you'll get a broader understanding looking at the [mkinitcpio installation hook](https://github.com/zbm-dev/zfsbootmenu/blob/master/initcpio/install/zfsbootmenu) and [run hook](https://github.com/zbm-dev/zfsbootmenu/blob/master/initcpio/hooks/zfsbootmenu) and, specifically, the [mkinitcpio entrypoint it creates](https://github.com/zbm-dev/zfsbootmenu/blob/master/initcpio/install/zfsbootmenu#L93-L113) rather than [the dracut module](https://github.com/zbm-dev/zfsbootmenu/blob/master/dracut/module-setup.sh), because the flow is a bit simpler in mkinitcpio; for dracut, we tie into its various run stages and you need an understanding of how that works. Either way, both the mkinicpio and dracut installers rely on [common installation functions](https://github.com/zbm-dev/zfsbootmenu/blob/master/zfsbootmenu/install-helpers.sh) to populate the components required by ZFSBootMenu.

At its most basic, the initramfs will first [parse the kernel command line](https://github.com/zbm-dev/zfsbootmenu/blob/master/zfsbootmenu/hook/zfsbootmenu-parse-commandline.sh) for options that govern ZBM behavior, then run a [pre-init](https://github.com/zbm-dev/zfsbootmenu/blob/master/zfsbootmenu/hook/zfsbootmenu-preinit.sh) script to set up some configuration and prepare a session, and finally [launch an init](https://github.com/zbm-dev/zfsbootmenu/blob/master/zfsbootmenu/libexec/zfsbootmenu-init) that will attempt to import pools (invoking early setup hooks if appropriate) and decide how to proceed. If an automatic boot isn't attempted (or is attempted and fails), the init pretty much just repeated alternates between launching [the main ZFSBootMenu script](https://github.com/zbm-dev/zfsbootmenu/blob/master/zfsbootmenu/bin/zfsbootmenu) to present a UI and allow interaction, or dropping to an emergency shell. (Pressing Ctrl+R in the ZBM user interface really just terminates the ZBM loop, allowing the init script to switch over to the emergency shell; exiting the emergency shell just allows the init script to switch back to launching the ZBM script.) In a normal session, this endless loop is only interrupted by a kexec that will jump into the chosen kernel.

If you would like further insight into the control flow, join us in the `#zfsbootmenu` IRC channel on libera.chat, or open up a [GitHub discussion](https://github.com/zbm-dev/zfsbootmenu/discussions).

**Comment by developer91234** [comment]
Thanks! The only question I still have right now is how exactly you're bundling your dependencies (namely the `fzf` executable) in the initramfs. This is something that's mystifying to me upfront because I don't see where it happening.

I'll use the channels you suggested if/when I have more substantive questions in future.

**Comment by ahesford** [comment]
The common installation routines define an [array of essential executables that includes fzf](https://github.com/zbm-dev/zfsbootmenu/blob/906ce3bf28dd27bd2d18164ef714dc3696e50197/zfsbootmenu/install-helpers.sh#L37).

The dracut setup module [installs those here](https://github.com/zbm-dev/zfsbootmenu/blob/906ce3bf28dd27bd2d18164ef714dc3696e50197/dracut/module-setup.sh#L58), and the [mkinitcpio hook installer here](https://github.com/zbm-dev/zfsbootmenu/blob/906ce3bf28dd27bd2d18164ef714dc3696e50197/initcpio/install/zfsbootmenu#L58).

**Comment by developer91234** [comment]
Aha! Not sure how I missed that lol. Thanks!
