### ISSUE TITLE
Encrypting /boot (evil maid attack)?

### ISSUE THREAD

**Issue by dm17** [zbm-dev/zfsbootmenu#36]
This is one of the most complete guides I've found:
https://gist.github.com/huntrar/e42aee630bee3295b2c671d098c81268

Any idea how your's would be modified to protect against the evil maid attack? I'd like to use the boot loaders you've already laid out.
Thanks!

**Comment by zdykstra** [comment]
I work around that issue by putting the EFI partition on a removable USB drive. Attach the drive to your key chain - put it in to boot the system and then take it out once the machine has been booted up. The process is documented in https://github.com/zdykstra/zfsbootmenu/blob/master/void-install.md . 

Otherwise, Void looks to have all the required tools to sign everything. There are kernel hooks in sbsigntool, but they point to files in /boot. Instead of signing files in /boot (those are already on an encrypted volume), you'd need to sign rEFInd and then the zfsbootmenu EFI files. The entire rest of the process looks more or less drop-in compatible with Void and zfsbootmenu.

**Comment by dm17** [comment]
Sweet, thanks! I'm guessing you have a backup/cloned USB drive - because if that one gets lost or breaks you're screwed, right?

Sounds like the signing could potentially be added after everything is setup.

**Comment by zdykstra** [comment]
After some discussion on #voidlinux on FreeNode, the official rEFInd documentation on Secure Boot also came up - https://www.rodsbooks.com/refind/secureboot.html . There's also work being done on https://github.com/Foxboron/sbctl as a better tool to do the entire process - though it's not quite ready for Void packaging. So it looks like all of the tools to sign everything do exist in some form on Void, but it will take a bit of research and experimentation to glue them all together.

**Comment by ericonr** [comment]
@dm17 with the new release, you should be able to sign EFI bundles. #34 has a rough description for how to do so.

**Comment by dm17** [comment]
> @dm17 with the new release, you should be able to sign EFI bundles. #34 has a rough description for how to do so.

Thanks, will try adding that after zdykstra's guide is finished.

@zdykstra I just installed the MBR onto the SSD - not going the USB drive route (trying secure boot instead). I left off on "Create an fstab entry and mount" - any idea what it would be? I'm guessing I can't just replace vfat with zfs...
Thanks.

**Comment by ahesford** [comment]
Closing because this can be accomplished with signing EFI bundles and is outside the purview of ZFSBootMenu itself.

**Comment by dm17** [comment]
> Closing because this can be accomplished with signing EFI bundles and is outside the purview of ZFSBootMenu itself.

Thanks! Have a recommended guide for signing EFI bundles? Or are you saying signing EFI bundles using another bootloader is the way it can be accomplished?
