### ISSUE TITLE
recovery: add additional tools/packages

### ISSUE THREAD

**Issue by zdykstra** [zbm-dev/zfsbootmenu#400]
* [x] ca-certificates so cURL supports SSL/TLS
* [x] wipefs so a disk can be completely trashed
* [x] sgdisk, possibly replacing gdisk

**Comment by ahesford** [comment]
I'd like to see `zbm-kcl` (especially the new one in #401) in all images by default, because people can use that in the recovery shell to edit KCL options for boot environments. When the new one is merged, we can also include objcopy to allow edits to EFI executables, but that is probably only useful for images that can mount FAT filesystems.

**Comment by csarn** [comment]
I would even suggest to include the void package manager, so anything you might need in the recovery environment can just be installed into the ramdisk.
