### ISSUE TITLE
ZBM does not allow snapshot revert if current FS has no kernel

### ISSUE THREAD

**Issue by Biyoni** [zbm-dev/zfsbootmenu#418]
If your only filesystem has no available kernel (for example, zfs failing to build on 6.2.8), ZBM dumps you into recovery shell only,

Even if you have snapshots available to revert to, you can only go to shell, making recovery more difficult than just promoting a snapshot from the menu

**Comment by ahesford** [comment]
This is because ZFSBootMenu only identifies "boot environments" as root filesystems (or legacy mounts that have been opted in) with kernels. Walking the snapshot history of any candidates to identify past kernels would be far too expensive to undertake in a pre-boot environment. Unfortunately, the only real option here is passing this off to the user for manual intervention.

**Comment by zdykstra** [comment]
We could possibly add a recovery shell tool that tab completes available environments and just calls [draw_snapshots](https://github.com/zbm-dev/zfsbootmenu/blob/master/zfsbootmenu/lib/zfsbootmenu-lib.sh#L232) . All of the action logic was moved to [snapshot_dispatcher](https://github.com/zbm-dev/zfsbootmenu/blob/master/zfsbootmenu/lib/zfsbootmenu-lib.sh#L340), so it wouldn't be too hard to call that after.

**Comment by ahesford** [comment]
That would be a great solution, and we welcome any contributions.
