### ISSUE TITLE
Also publish .iso file for zbm releases

### ISSUE THREAD

**Issue by csarn** [zbm-dev/zfsbootmenu#430]
Hi, thanks for your great project :)
I found myself building .iso-files with grub/syslinux and ZFSBootmenu so I can have zbm on a ventoy usb-stick (if you don't know, ventoy is a multiboot USB stick software, where you just copy .iso files on to the USB stick and then you can boot those isos). 
It would be great if such iso images could be made available automatically for new releases, as having zfsbootmenu available from an USB stick is really handy.

**Comment by csarn** [comment]
Disregard that, I didn't read the ventoy documentation carefully enough. It can already boot EFI images, so no need for an ISO :)

**Comment by claudiusraphael** [comment]
This request would actually make sense for the case where a EDK II / TianoCore DUET UEFI is necessary, either be it on a BIOS based system, or systems where the UEFI is corrupted or vendor-locked and never was updated or it comes with either a Hybrid UEFI (HP, GigaByte, Dell and others) or for example to allow utilizing all those nifty BayTrail/CherryTrail Tablets, Convertibles and ChromeBooks which come with a ia32/32-bit UEFI on a 64-bit system. For the latter it would be enormously helpful as only Fedora and some Debian-SpinOffs come by default with that bootia32.efi. Bundling a proven to be working with zbm 32-bit EDK UEFI would allow zbm to be the first-to-go-to consideration for the gazillions of these devices out there in the wild. Especially interesting for Arch Linux, which makes it almost impossible to create a working bootia32 that actually keeps working after a Kernel-change for example.

**Comment by ahesford** [comment]
Getting in the business of creating catch-all UEFI and syslinux loaders is beyond the scope of this project.

**Comment by claudiusraphael** [comment]
@ahesford I assumed that it is "not planned", hence no request to reopen this issue from me - but i felt it is noteworthy.

EDK II is regularly updated and most OEM UEFI is using it as base template to develop, build and test their modules against it.

An actual build is also used in the OpenCore Bootloader, which is utilized as a cross-platform (Mac OS, Windows, Linux - direct boot) Boot loader/manager and is often used in combination with the well established Refind for the case where a UEFI is already present or where firmware patches must be applied to correct the wrongdoing of a custom firmware or problems with register-handling or shadowing drivers.

"Catch-all UEFI" is already done therefore with that combination, and requires neither knowledge of syslinux nor of more exotic bootloaders. The only thing that is missing is a bootloader specific to zfs to complete the picture, which is zfsbootmenu, as alternative options either rely on utilizing Grub or Gummiboot/systemdboot built on top of these - whereas zbm is standalone and can be loaded cleanly as efi.

While i haven't touched zbm in a while for other than those systems i already have in use (simply due to lack of time to invest and unsuccessful attempts to use it on bios based systems as well as systems with custom and hybrid uefi when it got on the plan) it is no problem to use the edk ii/tianocore boot of opencore on these systems to chainload zbm in a standard-conform up to date uefi.

Anyhow do not be scared by the wall of text, this is simply a closing note to give those who might be interested in this some ideas where to look for.

**Comment by claudiusraphael** [comment]
@ahesford I assumed that it is "not planned", hence no request to reopen this issue from me - but i felt it is noteworthy.

EDK II is regularly updated and most OEM UEFI is using it as base template to develop, build and test their modules against it.

An actual build is also used in the OpenCore Bootloader, which is utilized as a cross-platform (Mac OS, Windows, Linux - direct boot) Boot loader/manager and is often used in combination with the well established Refind for the case where a UEFI is already present or where firmware patches must be applied to correct the wrongdoing of a custom firmware or problems with register-handling or shadowing drivers.

"Catch-all UEFI" is already done therefore with that combination, and requires neither knowledge of syslinux nor of more exotic bootloaders. The only thing that is missing is a bootloader specific to zfs to complete the picture, which is zfsbootmenu, as alternative options either rely on utilizing Grub or Gummiboot/systemdboot built on top of these - whereas zbm is standalone and can be loaded cleanly as efi.

While i haven't touched zbm in a while simply due to lack of time to invest and unsuccessful attempts to use it on bios based systems as well as systems with custom and hybrid uefi when it got on the plan, it is no problem to use the edk ii/tianocore boot of opencore on these systems to chainload zbm in a standard-conform up to date uefi.

Anyhow do not be scared by the wall of text, this is simply a closing note to  give those who might be interested in this some ideas where to look for.
