### ISSUE TITLE
Add support for environments where the "kernels" are directly at the root of a dataset

### ISSUE THREAD

**Issue by longsleep** [zbm-dev/zfsbootmenu#471]
Recently I converted my existing installation from grub2 to zfsbootmenu. I struggled a bit with zfsbootmenu not "finding kernels". My installation did not qualify numer 3 of the rules:

3. At least one of the scanned ZFS filesystems contains a /boot subdirectory that contains at least one paired kernel and initramfs.

This was not the case for me as I hade a dedicated pool for /boot where the stuff is at the base and not inside another /boot folder. (this setup is quite common for grub systems which were converted from older style with a dedicated boot partition.

Maybe a dedicated setting can be added which allows an environment to be defined directly inside the base of the dataset.

I solved my particular issue by getting rid of the extra pool and putting things into a boot folder of the root dataset with mountpoint / but doing that migration from the recovery shell was a bit tricky.

**Comment by ahesford** [comment]
Funny you should bring up the issue in this way, because I've been playing with improvements to kernel identification that would enable kernels to exist at the root of a boot environment. (With the improvements, supporting kernels at `/` is [effectively a one-line change](https://github.com/zbm-dev/zfsbootmenu/commit/1aa4a4f6f3c43a4e166132e83f9f1ca31acac13f).)

Unfortunately, that wouldn't help in your scenario:
1. You'd have to set your `/boot` filesystem to legacy mounting before ZBM would even identify it, because ZBM only inspects file systems with mountpoints of `/` or `legacy; and
2. Even if you trick ZBM into finding the `/boot` filesystem, it won't boot because ZBM will try to pass *that* as the `root=` argument to the kernel you launch, rather than the actual root.

The necessary changes to accomplish booting from your separate boot pool would either render half of ZBM functionality unusable (cloning, snapshot rollback, etc.) or require far too much magic in support of an unadvisabke configuration that is easy to remedy.

In your case, dropping the `/boot` mountpoint  and copying its contents directly into your root is the right approach.

**Comment by longsleep** [comment]
Thanks for the detailed explaination and glad to hear that what I did is actually "the way". I guess will update my [full disk encryption ZFS setup guide](https://gist.github.com/longsleep/48a585219e1c7b5d04b827ed02b029de) to use zfsbootmenu as it overall seems to simplify things quite a lot.

**Comment by Xavantex** [comment]
Newbie question to someone who is looking at some perhaps trivial hardening. I want to isolate /boot from executing, read-only, no special devices nor userid files, using ZBM for root. Is hacking ZBM the approach, I saw you had some luck with Alpine in one of your posts here @ahesford ?

**Comment by ahesford** [comment]
If you're separating /boot, you might as well just use something like `systemd-boot` and leave your kernels out of ZFS.

**Comment by Xavantex** [comment]
How so? In theory, why would a seperate dataset for boot be worse than systemd-boot? I might be missing some nuance here, but was that not what you were experimenting with? Or perhaps that is what you are saying, that you have found that to be the case?

**Comment by zdykstra** [comment]
ZFSBootMenu requires /boot to be part of the root dataset. Entertaining discussions of how to split that apart is well beyond the scope of this thread.

**Comment by ahesford** [comment]
My experiment with recognizing kernels in a filesystem root would not have enabled separate `/boot` filesystems. That would, as I noted, involve additional assumptions that would break about half of the features of ZFSBootMenu and isn't really a path worth pursuing.
