### ISSUE TITLE
Please re-instate Debian 11 documentation

### ISSUE THREAD

**Issue by stuart-mclaren** [zbm-dev/zfsbootmenu#492]
As a result of https://github.com/zbm-dev/zfsbootmenu/issues/489
the documentation for Debian 11 was removed.

I think this makes sense if zfsbootmenu is targeted at laptops with a single disk.

But typically zfs is more interesting if it's on a server, eg with a large JBOD attached.

Debian 11 is supported until 2026.

Currently, I'd guess 80%-90% of debian installs in data centres are going to be
11.x and not 12.x.  (I'd agree that for desktops, the 12.x ratio is probably much higher.)

(I'd also guess that more data centre installs are going to use Debian than some of
the other flavours you have documentation for - eg Fedora.)

So by removing the Debian 11 documentation any users installing servers are
going to have to switch to something other than zfsbootmenu - something that has documentation.

openzfs still has live documentation going back as far as Debian 9:

https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Stretch%20Root%20on%20ZFS.html

Its Debian 11 documentation won't be going away any time soon.

If I were a member of the zfsbootmenu team (rather than a random voice on the internet that
probably knows nothing about anything...), I would consider the time (minutes?) spent re-instating
the Debian 11 docs to be time well spent -- if the project wants to retain this particular class of users.

(Again, unless zfsbootmenu is focussed on single disk laptop installs.)

Thanks.

**Comment by ahesford** [comment]
There is nothing particularly special about our installation guides. They tell you how to install (in this case, some version of Debian) pretty much according to the upstream process. The key differences are:

1. We don't tell users to add a separate "boot pool" for GRUB compatibility. Not only is this not required for ZFSBootMenu, but it is absolutely terrible advice for a number of reasons. Users who want a ZFS root without ZFSBootMenu should just put `/boot` on a more common filesystem with sensible support from their bootloader of choice.
2. At the end, we tell people to download a ZFSBootMenu EFI executable and configure the system to boot it.

Both of these points are readily adaptable to any of the guides for any Linux-on-ZFS installation guide across the internet. Furthermore, ZFS is advanced enough that people using it ought to be able to figure out how *not* to split the `/boot` directory during installation and how to copy an EFI executable and tell a machine to boot it. This is especially true of professionals managing data centers.

We think our guides are the best available Linux-on-ZFS guides. However, our goal is to provide quick references for people to get going. We prefer to spend time refining the boot process rather than providing long-term support for installation documents for distributions with tooling that fall ever further behind. (We fight this battle enough in the bootloader itself---ZBM has a bunch of feature checks that exist **only** to accommodate the years-old tooling that ships in Debian hosts.)

**Comment by ahesford** [comment]
Also note:
- The guide notes that the `compatibility` flag is optional and intended as a guard against blindly adopting breaking changes in your pool with new ZFS releases.
- The Debian 11 guide will continue to be available on the docs website by default until we cut a 2.3 release, and after that by navigating to the `v2.2.x` docs using the built-in version selector.

**Comment by ahesford** [comment]
It's always puzzling to hear people show up from time to time to argue about increasing user adoption. I doubt any of us cares much about the adoption of ZFSBootMenu, and I know for a fact that I don't. That other people might find ZFSBootMenu useful is a nice bonus. I welcome people along for the ride, but it wouldn't make any difference to me if nobody outside of this team used the project. 

This is a hobby project. I work on it because I enjoy thinking about how to improve the boot process, and I want to build software that I actually use. The project has brought me opportunities to cultivate friendships and collobrate with people at my leisure. Sometimes, I effectively ignore ZFSBootMenu for weeks or months because I don't see any interesting challenges. However, I relish time spent almost every day talking with the team as well as a handful of dedicated users and project observers.

The narrowly conceived cost of maintaining a separate guide may or may not be negligible. We've spent considerable effort making the documentation modular and easily extensible, and the fact that Debian 11 is now an outlier with respect to a compatibility option means we'd need to separate that document from the reusable components, complicating the adoption of further fixes or other enhancements and demanding ongoing effort to address new issues that might come up with a constantly aging Debian release. The complexity of this is compounded by the fact that none of us uses Debian with ZFSBootMenu, so we spend extra time finding a suitable test environment to verify the documentation we post. As you've seen, this can sometimes lead to small details falling through the cracks.

The broader cost of maintaining guides is the fact that, when we decide it's time to sunset them, we spend time responding to argumentative users keen on telling us why our decisions are wrong. This saps enthusiasm for hobby work and, over time, can be fatal to projects.

We are simply not interested in maintaining a Debian 11 guide. When you opened the initial issue, we discussed the matter internally and decided our preferred course was the removal of a guide that we hadn't thoroughly tested and did not wish to continue supporting.

If the lack of Debian 11 documentation will prevent you from using ZFSBootMenu, I wish you the best.

**Comment by zdykstra** [comment]
@stuart-mclaren I've read, and re-read your most recent reply a number of times now.  You seem to be arguing from a position of bad faith. As much as I'd like to reply to each argument and snide comment, I don't consider that to be a good use of my time. You'll note, of course, that I'm the arbiter of how my time should be spent - not you.
