### ISSUE TITLE
Unsupported Features Detected in ZFSBootMenu After Arch Linux Update

### ISSUE THREAD

**Issue by Doraemonsan** [zbm-dev/zfsbootmenu#624]
### ZFSBootMenu build source

Release EFI

### ZFSBootMenu version

2.3.0

### Problem description

Hey guys, I've set up Arch Linux with a ZFS root partition and am using zfsbootmenu as my bootloader. Today, after running pacman -Syu and zpool upgrade to update my system and rebooting, zfsbootmenu started showing the message "Unsupported features detected. Upgrade ZFS modules in ZFSBootMenu with generate-zbm" and it waits for 30 seconds. This warning doesn’t seem to stop my system from booting normally, but I can’t make any changes to my ZFS pool from within zfsbootmenu—it seems to only mount the pool as read-only.

Here are the versions of my system environment:
* ArchLinux Kernel : 6.6.29-1-lts
* zfs module(dkms) : 2.2.3-1
* zfsbootmenu(releases) : zfsbootmenu-release-x86_64-v2.3.0-vmlinuz.EFI
![{108D1250-A921-4c2c-9EDB-F3EECEAACD3E}](https://github.com/zbm-dev/zfsbootmenu/assets/21234683/21f09bb3-7584-4ce5-8d58-0cd6b28bf959)
![{2C26D823-6727-42ce-865D-CD122596F20B}](https://github.com/zbm-dev/zfsbootmenu/assets/21234683/ace04421-d018-40fd-85ff-1b9eb8aa2262)

### Steps to reproduce

1.Update the system with pacman -Syu.
2.Upgrade the ZFS pool with zpool upgrade.
3.Reboot the system using reboot.

**Comment by classabbyamp** [comment]
the prebuilt image for zfsbootmenu 2.3.0 should have zfs 2.2.2 on it, and zfs 2.2.3 didn't introduce any new feature flags. are you sure you were running zfs 2.2.x when you upgraded the pool?

**Comment by Doraemonsan** [comment]
> zfsbootmenu 2.3.0 的预构建映像应该包含 zfs 2.2.2，而 zfs 2.2.3 没有引入任何新功能标志。您确定升级池时正在运行 zfs 2.2.x 吗？

One thing I know for sure is that I was running ZFS version 2.2x when I upgraded the zpool. I received the following message during the upgrade, hope this helps you out


This system supports ZFS pool feature flags.
﻿
All pools are formatted using feature flags.
﻿
Some supported features are not enabled on the following pools. Once a
feature is enabled the pool may become incompatible with software
that does not support the feature. See zpool-features(7) for details.
﻿
Note that the pool 'compatibility' feature can be used to inhibit
feature upgrades.
﻿
POOL  FEATURE
---------------
zroot
redaction_list_spill
raidz_expansion

**Comment by ahesford** [comment]
The [upstream list of feature flags](https://openzfs.github.io/openzfs-docs/Basic%20Concepts/Feature%20Flags.html) shows that these two features are incompatible with ZFS 2.2.3. Your problem is probably that Arch (or the AUR) plays too fast and too loose with patches. ZFSBootMenu is working as expected here, doing its level best (and succeeding) to boot your system while warning you that you're at the edge of danger.

If you're going to use the prebuilt ZBM image, we recommend (as in all of our installation guides) that you use compatibility flags to lock the pool at a version your ZBM image will support. If you upgrade your pool beyond that, you need to create your own ZFSBootMenu image with the same (or newer) version of ZFS.
