### ISSUE TITLE
<dataset> "is already mounted" printing in a loop; the boot menu never loads

### ISSUE THREAD

**Issue by redaphid** [zbm-dev/zfsbootmenu#83]
Hey, first off: Thanks for making this project! It's nice to know that there's other people that obsess over this stuff as much as I do.
![zfsbootmenu-already-mounted](https://user-images.githubusercontent.com/4147669/94507989-d3e33500-01c5-11eb-8bd8-ba176d1b4afb.png)

I've been spending the last few days off and on debugging an issue I'm running into in which the `zfsbootmenu` Repeatedly prints "filesystem <dataset> is already mounted". 

Any idea what could be causing it? It's keeping me from booting my system right now :/ Enclosed is a screenshot of the error.

Thanks for your help, and this totally awesome project.

**Comment by zdykstra** [comment]
I'll be glad to help track down what's happening here! Can you provide a few details about the problem:

* What OS are you booting?
* When specifically does this error show up in the boot process? (Inside ZFSBootMenu, when booting the target OS/Boot environment, etc) 
* What version of ZFSBootMenu are you using?

Once I have a few basics established I'll probably have a few more questions to help narrow down what is happening. We do have an IRC channel on Freenode - `#zfsbootmenu`. There are a couple of us there, so if you idle/lurk in there you can catch someone.

**Comment by redaphid** [comment]
Hey! Thanks for your response! Let me see what info I can give you:

- What OS are you booting?
I'm trying to boot Ubuntu, which did some craziness when it comes to creating datasets, etc. I placed it's kernel in /boot, so at least zfsbootmenu can find them.

- When specifically does this error show up in the boot process? (Inside ZFSBootMenu, when booting the target OS/Boot environment, etc)
Actually, this happens before the boot menu even shows up. The message prints repeatedly, instead of showing the boot menu.

- What version of ZFSBootMenu are you using?
Looks like it's 1.5.0

IRC sounds like a pretty good idea :). I'm actually still fighting this as we speak!

**Comment by zdykstra** [comment]
Can you provide the full output `zfs list -o name,canmount,mountpoint` on the system? I'm looking for everything Ubuntu sets up, as well as what your Void setup is.  Thanks!

**Comment by ahesford** [comment]
While you're are it, please also post the contents of `/etc/zfsbootmenu/dracut.conf.d/zfsbootmenu.conf` (and any other files in that directory) and `/etc/zfsbootmenu/config.yaml`.

**Comment by buenyamin0** [comment]
I have the same problem when booting the target os

**Comment by zdykstra** [comment]
> I have the same problem when booting the target os

Can you provide the full output zfs list -o name,canmount,mountpoint on the system? As well as the contents of `/etc/zfsbootmenu/dracut.conf.d/zfsbootmenu.conf` and `/etc/zfsbootmenu/config.yaml` ? Please also let me know which distribution is in the boot environment (Void, Ubuntu, ??). Thanks!

**Comment by buenyamin0** [comment]
`NAME               CANMOUNT  MOUNTPOINT
zroot                       off  none
zroot/boot                   on  /boot
zroot/home                   on  /home
zroot/home/root              on  /root
zroot/home/user                 on  /home/user
zroot/ROOT                  off  none
zroot/ROOT/x             noauto  /
zroot/usr                   off  none
zroot/usr/local              on  /usr/local
zroot/var                   off  none
zroot/var/log                on  /var/log

nofsck="yes"
add_dracutmodules+=" zfsbootmenu "
omit_dracutmodules+=" btrfs zfs resume systemd systemd-initrd dracut-systemd "

Global:
  ManageImages: true
  BootMountPoint: /boot/efi
  DracutConfDir: /etc/zfsbootmenu/dracut.conf.d
Components:
  ImageDir: /boot/efi/EFI/void
  Versions: 3
  Enabled: true
  syslinux:
    Config: /boot/syslinuzroot/syslinux.cfg
    Enabled: false
EFI:
  ImageDir: /boot/efi/EFI/void
  Versions: false
  Enabled: false
Kernel:
  CommandLine: ro quiet loglevel=0
`

**Comment by zdykstra** [comment]
`zroot/boot` shouldn't exist - ZFSBootMenu expects `/boot` to be a regular directory inside each boot environment. Having it exist outside of a boot environment in many ways negates the purpose of BEs. 

Once the contents of that filesystem are copied to a regular `/boot` directory inside the boot environment, and then `zroot/boot` is set to canmount=noauto, please let me know what happens when booting.

**Comment by buenyamin0** [comment]
thanks, it is working now
however I have another issue,
somehow when  trying to startx or xfce I am just getting a blank screen,

its working when booting without zfsbootmenu though

it is also taking some time until the keyboard is available for typing in the password for the zpool 
not sure why that is

**Comment by zdykstra** [comment]
> thanks, it is working now
> however I have another issue,
> somehow when trying to startx or xfce I am just getting a blank screen,
> 
> its working when booting without zfsbootmenu though
> 
> it is also taking some time until the keyboard is available for typing in the password for the zpool
> not sure why that is

What hardware do you have in your system - specifically which GPU and driver do you use?

**Comment by ahesford** [comment]
There could be a couple of things going on here. First, I'd double check that your kernel command line is set the same when you use ZFSBootMenu and when you use whatever other method doesn't cause problems. Maybe you've overlooked some setting necessary to satisfy your video hardware or its kernel drivers.

Another possibility is interference between the ZFSBootMenu kernel and the main system kernel, since we use `kexec` to launch the new kernel and that doesn't leave hardware in the same state as a cold boot. I have a laptop with Intel graphics and, if I don't boot ZFSBootMenu with `nomodeset` and `i915.modeset=0`, the main system kernel will complain about video hardware when it boots. (I don't know if this has any affect on X11, but it certainly dumps some debugging information to the console at boot time.) You can try playing with `nomodeset` in ZBM or blacklisting your video drivers in the ZBM initramfs to minimize the chance of interference.

**Comment by buenyamin0** [comment]
I have a GTX 770 and did not install the nvidia drivers yet
so it is using the standard drivers that come with xorg I think

and about the commandline, I have not changed any of the zfsbootmenu settings

its just "spl_hostid=hostid ro quiet"

and with the other method there are  no options other than the root zfs
